### ISSUE TITLE
Får inte det att fungera som knapp

### ISSUE THREAD

**Issue by Maltavius** [lindell/home-assistant-svt-play#1]
Om man vill ha en knapp som startar svtbarn och knappen syns bara om TVn är på.
---LOVELACE---
card:
  entity: script.tv_channel_barnkanalen
  hold_action:
    action: none
  icon: 'mdi:flower'
  name: Barnprogram
  service: script.turn_on
  show_icon: true
  show_name: true
  tap_action: call-service
  type: entity-button
conditions:
  - entity: media_player.samsung_ue50es6715
    state: 'on'
type: conditional

--- SCRIPT---

tv_channel_barnkanalen:
  alias: Barnkanalen
  sequence:
  - data:
      channel: svtbarn
    entity_id: media_player.vardagsrummet
    service: svt_play.play_channel

Ska inte det fungera?

----LOG---

Logger: homeassistant.components.script
Integration: Script (documentation, issues)
First occured: 12:16:55 PM (1 occurences)
Last logged: 12:16:55 PM

Error executing script script.tv_channel_barnkanalen. Invalid data for call_service at pos 1: extra keys not allowed @ data['data']

**Comment by lindell** [comment]
When you call the service, it should look like this:
```yaml
- service: svt_play.play_channel
  entity_id: media_player.vardagsrummet
  data:
    channel: svtbarn
```

**Comment by Maltavius** [comment]
That's what I had but I didn't realise that github ruined the indentation.

Well I had it in a different order, but that's how HA changes the rows around when not editing the scripts.yaml manually...

I kind of got it to work now, what does it use for a client anyways?
When playing it doesn't show up on my Phones as "Playing on your Chromecast"

**Comment by lindell** [comment]
> what does it use for a client anyways

Not really sure what you mean. It does fetch the media url and then uses the Hass [media_player.play_media](https://github.com/lindell/home-assistant-svt-play/blob/master/custom_components/svt_play/__init__.py#L86) service to start it. 

> When playing it doesn't show up on my Phones as "Playing on your Chromecast"

I would also like media started through home assistant to show up as "Playing on your Chromecast" but that's unfortunately something that home assistant / google have to fix.
