### ISSUE TITLE
Chromecast doesn't resolve channels - and solution

### ISSUE THREAD

**Issue by Cybersmurfen** [lindell/home-assistant-svt-play#10]
I noticed that since at least few days ago, CC gen 3 doesn't recognize the stream and HA throws an error.

It looks like CC doesn't accept the dashhbbtv-url anymore, but it works fine with the hls one.
The solution is to change the format-order in video_fetch.py Ln8 to

default_formats = ['hls', 'dashhbbtv', 'hls-cmaf']
(Instead of dashhbbtv first)

I did not made any commit - see below:

In fact, I cannot ask Google Assistant to play a channel from SVT play on a CC, so I guess it is or will be general problem - I have no idea if anything changed in the API, the DashHBB-URL is faulty or if the CC was updated in some way.

**Comment by lindell** [comment]
The code is prepared to allow you to set the formats you want, the data just needs to be added as settings. Might look into it later during the weekend.

I general, I'm no expert in video formats/codex and don't know which format is "best" and which is supported by most. The default order maybe should change?

**Comment by lindell** [comment]
Since I got no answer to the question I went with `'hls', 'dash'` as the priority. #12
