### ISSUE TITLE
play_url is not supported (svt1)

### ISSUE THREAD

**Issue by jibbic** [lindell/home-assistant-svt-play#14]
Trying to set up for the first time.  From what I understand from the logs, the error is "play_url is not supported" ? Never used this before, so not sure if I'm doing anything wrong, or SVT changed anything on there end? 

Not sure if helpful or not, I tried to use svtplay.dl to get the the url:

Run:
svtplay-dl -g -P DASH https://www.svtplay.se/kanaler/svt1
Result:
https://svt1-c.akamaized.net/se/svt1/manifest.mpd?defaultSubLang=1

And this URL differs from the one in the log (https://svt1-c.akamaized.net/se/svt1/master.m3u8?defaultSubLang=1). But I'm not sure I'm getting the correct url from svtplay.dl

--- Automation --- 
alias: Svt
description: Spela svt i vardagsrummet
trigger: []
condition: []
action:
  - service: svt_play.play_channel
    entity_id: media_player.vardagsrum
    data:
      channel: svt1

------ Logg -----

Logger: homeassistant.core
Source: components/apple_tv/media_player.py:176 
First occurred: 26 september 2021 23:04:54 (14 occurrences) 
Last logged: 0:31:04

Error executing service: <ServiceCall media_player.play_media (c:fcfcb44773b68bf2959a375acfb0339c): entity_id=['media_player.vardagsrum'], extra=, media_type=video, media_id=https://svt1-c.akamaized.net/se/svt1/master.m3u8?defaultSubLang=1>
Error executing service: <ServiceCall media_player.play_media (c:76bb73761af90972762985a45846ffaf): entity_id=['media_player.vardagsrum'], extra=, media_type=video, media_id=https://svt1-c.akamaized.net/se/svt1/master.m3u8?defaultSubLang=1>
Error executing service: <ServiceCall media_player.play_media (c:ca6b145f385e68cd289c14a7b630b759): entity_id=['media_player.vardagsrum'], extra=, media_type=video, media_id=https://svt-vod-9q.akamaized.net/d0/world/20210926/498a0bfc-b872-4fb4-9b91-6caa7074fe75/hls-ts-avc.m3u8?alt=https%3A%2F%2Fswitcher.cdn.svt.se%2F498a0bfc-b872-4fb4-9b91-6caa7074fe75%2Fhls-ts-avc.m3u8>
Error executing service: <ServiceCall media_player.play_media (c:6220c860d7d55fa84ef0436df5b34888): entity_id=['media_player.vardagsrum'], extra=, media_type=video, media_id=https://svt1-c.akamaized.net/se/svt1/master.m3u8?defaultSubLang=1>
Error executing service: <ServiceCall media_player.play_media (c:77b3b63a1c39a3602afdc883e99b9dc4): entity_id=['media_player.vardagsrum'], extra=, media_type=video, media_id=https://svt1-c.akamaized.net/se/svt1/master.m3u8?defaultSubLang=1>
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/core.py", line 1507, in catch_exceptions
    await coro_or_task
  File "/usr/src/homeassistant/homeassistant/core.py", line 1526, in _execute_service
    await handler.job.target(service_call)
  File "/usr/src/homeassistant/homeassistant/helpers/entity_component.py", line 213, in handle_service
    await self.hass.helpers.service.entity_service_call(
  File "/usr/src/homeassistant/homeassistant/helpers/service.py", line 658, in entity_service_call
    future.result()  # pop exception if have
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 856, in async_request_call
    await coro
  File "/usr/src/homeassistant/homeassistant/helpers/service.py", line 695, in _handle_entity_call
    await result
  File "/usr/src/homeassistant/homeassistant/components/apple_tv/media_player.py", line 176, in async_play_media
    await self.atv.stream.play_url(media_id)
  File "/usr/local/lib/python3.9/site-packages/pyatv/support/facade.py", line 326, in play_url
    await self.relay("play_url")(url, **kwargs)
  File "/usr/local/lib/python3.9/site-packages/pyatv/support/relayer.py", line 75, in relay
    instance = self._find_instance(target, priority or self._priorities)
  File "/usr/local/lib/python3.9/site-packages/pyatv/support/relayer.py", line 97, in _find_instance
    raise exceptions.NotSupportedError(f"{target} is not supported")
pyatv.exceptions.NotSupportedError: play_url is not supported

**Comment by lindell** [comment]
What kind of media player is `media_player.vardagsrum`? My guess is that you are using a media player that is very picky with the format. What happens if you change the order of the items here, then reload home assistant and try again.

https://github.com/lindell/home-assistant-svt-play/blob/master/custom_components/svt_play/video_url_fetch/video_fetch.py#L8

**Comment by postlund** [comment]
This is an Apple TV. I would suggest that you either hold off for a while or try the beta component (https://github.com/postlund/hass-atv-beta) as I'm making lots of improvements. Hopefully this bug will be solved by that.

I will make a new update to the component later tonight, so I suggest you wait until then as it contains fixes to a few issues we are seeing right now.

**Comment by lindell** [comment]
Thanks for the information @postlund. This should be a problem with the apple tv integration then? And we can safely close this issue?

Also, how did you find this issue? 🙂  Do you have alerts for "pyatv" comments on GitHub?

**Comment by postlund** [comment]
Yeah, this is an Apple TV integration issue for sure! AirPlay isn't set up properly (either pairing failed or the service isn't discovered properly).

I found it by pure chance actually. Was looking for an issue in another project mentioning pyatv, so I was searching for it and ended up here 😊

**Comment by lindell** [comment]
Good timing then I guess, since this issue was created hours before your response 😛

**Comment by postlund** [comment]
Indeed! 😉

**Comment by jibbic** [comment]
Perfect :)

First time posting in GitHub, was not disappointed, big thanks! ☺️
