### ISSUE TITLE
Doesn't play anything

### ISSUE THREAD

**Issue by AzzMG** [lindell/home-assistant-svt-play#20]
I was thinking about to make Den stora älgvandringen start during my homes ordinary morning routines and was quite joyful when I found your project.

However, I installed in with HACS and made a script that executes without any errors but nothing happens.

Tried to run other programs (like Rapport) and on different media players (LG-tv and Firestick) and on the Firestick it runs without an error but in the log get an error about it is not supported.

Code:
`alias: SVT - Den stora älgvandringen
sequence:
  - service: svt_play.play_suggested
    data:
      entity_id: media_player.fire_tv
      program_name: rapport
mode: single
icon: mdi:forest
`

Log from mediaplayer.fire_tv
Logger: homeassistant.core
Source: helpers/service.py:663
First occurred: 08:12:16 (5 occurrences)
Last logged: 08:43:03

Error executing service: <ServiceCall media_player.play_media (c:01GZAZ1EXHJVEFT25RJH03AD53): entity_id=['media_player.fire_tv'], extra=title=Rapport - Igår 22:50, thumb=https://www.svtstatic.se/image/large/1024/39584127/1682888536?format=auto&chromaSubSampling=false, media_type=video, media_id=https://svt-vod-10k.akamaized.net/d0/world/20230430/19b27dc7-15c1-4f46-9abd-a24fe415e302/hls-ts-avc.m3u8>
Error executing service: <ServiceCall media_player.play_media (c:01GZAZS9F5MT0SYJYD90D8EAFV): entity_id=['media_player.fire_tv'], extra=title=Svenska nyheter - Fre 3 mar 22:00, thumb=https://www.svtstatic.se/image/large/1024/38825831/1677878129?format=auto&chromaSubSampling=false, media_type=video, media_id=https://svt-vod-6j.akamaized.net/d0/world/20230304/0ce92cde-b973-4a1f-80d4-00aa6687006c/hls-ts-avc.m3u8>
Error executing service: <ServiceCall media_player.play_media (c:01GZB0DHBDNB3H685THRBVEFPB): entity_id=['media_player.fire_tv'], extra=title=Rapport - Igår 22:50, thumb=https://www.svtstatic.se/image/large/1024/39584127/1682888536?format=auto&chromaSubSampling=false, media_type=video, media_id=https://svt-vod-10k.akamaized.net/d0/world/20230430/19b27dc7-15c1-4f46-9abd-a24fe415e302/hls-ts-avc.m3u8>
Error executing service: <ServiceCall media_player.play_media (c:01GZB0GBT7E90E8TVPQYXS4TR4): entity_id=['media_player.fire_tv'], extra=title=Rapport - Igår 22:50, thumb=https://www.svtstatic.se/image/large/1024/39584127/1682888536?format=auto&chromaSubSampling=false, media_type=video, media_id=https://svt-vod-10k.akamaized.net/d0/world/20230430/19b27dc7-15c1-4f46-9abd-a24fe415e302/hls-ts-avc.m3u8>
Error executing service: <ServiceCall media_player.play_media (c:01GZB0SV0APKQ8W069QAW0FDRE): entity_id=['media_player.fire_tv'], extra=title=Rapport - Igår 22:50, thumb=https://www.svtstatic.se/image/large/1024/39584127/1682888536?format=auto&chromaSubSampling=false, media_type=video, media_id=https://svt-vod-10k.akamaized.net/d0/world/20230430/19b27dc7-15c1-4f46-9abd-a24fe415e302/hls-ts-avc.m3u8>
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/core.py", line 1826, in catch_exceptions
    await coro_or_task
  File "/usr/src/homeassistant/homeassistant/core.py", line 1845, in _execute_service
    await cast(Callable[[ServiceCall], Awaitable[None]], handler.job.target)(
  File "/usr/src/homeassistant/homeassistant/helpers/entity_component.py", line 213, in handle_service
    await service.entity_service_call(
  File "/usr/src/homeassistant/homeassistant/helpers/service.py", line 663, in entity_service_call
    raise HomeAssistantError(
homeassistant.exceptions.HomeAssistantError: Entity media_player.fire_tv does not support this service.

Code is exactly the same for the LG-tv and it runs without an error but nothing happens.

**Comment by lindell** [comment]
On all of your devices, but especially the fire stick. Can you use the media_player.play_media service to play any type of video? The logs seems to indicate that it should not work.

**Comment by AzzMG** [comment]
Ahh.. Quite stupid of me...

The media player need to be a cast enabled device.

It's working on the kids cromecast

**Comment by lindell** [comment]
Indeed :) But it supprised me that the fire stick does not allow you to play any external video source.
