### ISSUE TITLE
channel id for Barnkanalen

### ISSUE THREAD

**Issue by jonatanjacobsson** [lindell/home-assistant-svt-play#21]
Wonderful plugin you guys have made! thanks!
I noticed setting this up that the channel id for Barnkanalen has been changed. it no longer works with "svtbarn", it need to be "barnkanalen". so if you want you can update the README, that would be great :)

**Comment by lindell** [comment]
Thanks for the notice! :) 

More out of principle. Please create a PR for this that I would happily merge.
