### ISSUE TITLE
svt1

### ISSUE THREAD

**Issue by perahlgren** [lindell/home-assistant-svt-play#8]
Hi,

This have worked fine until some days ago. I use it all the time, but just a week ago svt1 stopped working. Svt2 still works and program like rapport. Any changes?

**Comment by lindell** [comment]
No changes are made. I just tested with

```yaml
entity_id: media_player.kitchen_display
channel: svt1
```

And it worked fine. 

Without a way to reproduce it, I can't fix anything. If you still have this problem, please provide a way to reproduce it and reopen this issue.

**Comment by perahlgren** [comment]
It works fine again.

Skaffa Outlook för Android<https://aka.ms/ghei36>

________________________________
