### ISSUE TITLE
Detected I/O inside the event loop

### ISSUE THREAD

**Issue by snatcher** [lindell/home-assistant-svt-play#9]
Hello,

I'm getting this error since a while now, it still works fine but cannot see it reported anywhere, so here we go.

`WARNING (MainThread) [homeassistant.util.async_] Detected I/O inside the event loop. This is causing stability issues. Please report issue to the custom component author for svt_play doing I/O at custom_components/svt_play/video_url_fetch/video_fetch.py, line 125: data = post('https://api.svt.                                                                             se/contento/graphql', json=query_data).json()`

`WARNING (MainThread) [homeassistant.util.async_] Detected I/O inside the event loop. This is causing stability issues. Please report issue to the custom component author for svt_play doing I/O at custom_components/svt_play/video_url_fetch/video_fetch.py, line 24: data = get(url).json()`

**Comment by lindell** [comment]
#11 should fix this. Can you please verify that it does? :)

**Comment by lindell** [comment]
Assuming this is working. Please open otherwise.
